# Generated by Django 2.1.7 on 2024-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
